name: Lint
on:
  push:
    branches:
      - main
    tags:
      - "**"

permissions:
  contents: write

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup HOST_PROJECT_PATH variable
        run: echo "HOST_PROJECT_PATH=$(echo $(pwd))" >> $GITHUB_ENV
      - name: Setup tag value from new tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=${{github.ref_name}}" >> $GITHUB_ENV
      - name: Setup tag value from push on main
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Test Tag value
        run: echo ${{ env.IMAGE_TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: php-fpm.prod.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m2-ci-cd-symfony:${{ env.IMAGE_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: nginx.prod.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m2-ci-cd-nginx:${{ env.IMAGE_TAG }}
      - name: Create release notes on tag push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes