name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup HOST_PROJECT_PATH variable
        run: echo "HOST_PROJECT_PATH=$(echo $(pwd))" >> $GITHUB_ENV
      - if: startsWith(github.ref, 'refs/heads/main')
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: startsWith(github.ref, 'refs/heads/main')
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: $HOST_PROJECT_PATH/php-fpm.prod.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m2-ci-cd-symfony:latest
      - if: startsWith(github.ref, 'refs/heads/main')
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: $HOST_PROJECT_PATH/nginx.prod.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m2-ci-cd-nginx:latest
