name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup HOST_PROJECT_PATH variable
        run: echo "HOST_PROJECT_PATH=$(echo $(pwd))" >> $GITHUB_ENV
      - name: Install php dependencies
        run: docker run --rm --volume $HOST_PROJECT_PATH/app:/app composer install
      - name: PHP Linter
        run: make php-lint HOST_PROJECT_PATH=$HOST_PROJECT_PATH
      - name: PHP Testing
        run: docker run --rm --volume $HOST_PROJECT_PATH/app:/app php bin/phpunit
      - name: Build images
        run: docker compose build
