name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup HOST_PROJECT_PATH variable
        run: echo "HOST_PROJECT_PATH=$(echo $(pwd))" >> $GITHUB_ENV
      - name: install php dependencies
        run: docker run --rm --volume $HOST_PROJECT_PATH/app:/app composer install
      - run: make php-lint HOST_PROJECT_PATH=$HOST_PROJECT_PATH
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install php dependencies
        run: docker run --rm --volume $HOST_PROJECT_PATH/app:/app composer install
      - name: Début des images
        run: docker compose build