name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup HOST_PROJECT_PATH variable
        run: echo "HOST_PROJECT_PATH=$(echo $(pwd))" >> $GITHUB_ENV
      - name: Install php dependencies
        run: make install-dependencies
      - name: PHP Linter
        run: make lint
      - name: PHP Testing
        run: make tests
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: php-fpm.prod.dockerfile
      - name: Build image Symfony
        run: make build-symfony
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: php-fpm.prod.dockerfile
      - name: Build image Nginx
        run: make build-nginx
