name: Lint
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: make php-lint HOST_PROJECT_PATH=$(pwd)